/**
 * Layout raíz obligatorio de la app (app/layout.tsx).
 * Envuelve TODAS las páginas del proyecto (comparte <html>/<body>, fuentes, etc.).
 * Se renderiza como Server Component y no se vuelve a montar entre navegaciones,
 * por eso su estado se preserva al cambiar de ruta.
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
