/**
 * Layout raíz obligatorio de la app (app/layout.tsx).
 * Envuelve TODAS las páginas del proyecto (comparte <html>/<body>, fuentes, etc.).
 * Se renderiza como Server Component y no se vuelve a montar entre navegaciones,
 * por eso su estado se preserva al cambiar de ruta.
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <header className="site-header">
          <Link href="/" className="site-header__brand">
            <Image
              src="/logo.png"
              alt="Hotel"
              width={328}
              height={61}
              priority
              className="site-header__logo"
            />
          </Link>
        </header>
        <main className="site-main">{children}</main>
      </body>
    </html>
  );
}
