/**
 * Layout raíz obligatorio de la app (app/layout.tsx).
 * Envuelve TODAS las páginas del proyecto (comparte <html>/<body>, fuentes, etc.).
 * Se renderiza como Server Component y no se vuelve a montar entre navegaciones,
 * por eso su estado se preserva al cambiar de ruta.
 */
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { logoutAction } from "@/modules/auth/auth.actions";
import { getSession } from "@/modules/auth/auth.session";
import { USER_ROLE_LABELS } from "@/modules/users/user.labels";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  // Al leer la cookie de sesión el layout pasa a renderizarse por request:
  // es lo que permite mostrar quién está conectado en todas las páginas.
  const session = await getSession();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        <header className="site-header">
          <Link href="/" className="site-header__brand">
            <Image
              src="/logo.png"
              alt="Hotel"
              width={328}
              height={61}
              priority
              className="site-header__logo"
            />
          </Link>

          {session && (
            <div className="site-header__session">
              <span className="site-header__user">
                {session.name ?? "Usuario"}
                <span className="site-header__role">
                  {USER_ROLE_LABELS[session.role]}
                </span>
              </span>

              {/* Server Action: cierra sesión sin necesidad de JavaScript. */}
              <form action={logoutAction}>
                <button type="submit" className="site-header__logout">
                  Cerrar sesión
                </button>
              </form>
            </div>
          )}
        </header>
        <main className="site-main">{children}</main>
      </body>
    </html>
  );
}
